### ISSUE TITLE
Add Support for Husky v6

### ISSUE THREAD

**Issue by andrewtcobb** [chiptopher/guet#104]
## Feature Request
Update docs to reflect changes made with Husky v6 and add automatic support for the new Husky changes.

#### Description
In Husky v6, major changes were made to how Husky hooks are created. These changes, along with their rationale, are explained in [this article](https://blog.typicode.com/husky-git-hooks-javascript-config/).

Hooks are no longer configured from the package.json, like the current FAQ page suggests. For now, to use Guet with Husky v6, you must define your hooks in your `.husky` folder, then add the guet committer check to whichever hooks you would like. It would be great if the existing `guet start -a` command did this wiring for you like it currently does for older versions of Husky.

**Comment by chiptopher** [comment]
Suppose you could do something like `guet start -a --location .husky`, would that work? That way you could dump the hooks wherever you wanted? You'd still have to do `npx husky add .husky/pre-commit "./guet-pre-commit"` to add it to the appropriate husky file, but I'd rather keep code specific to working with husky out of guet.

**Comment by andrewtcobb** [comment]
I think that would be perfect. We just did the `npx husky add .husky/hook-name "./guet-some-kind-of-hook"` and it worked fine, and I wouldn't necessarily expect guet to handle something that specific to Husky. Being able to change where the hooks go would be nice though, and would also help support the `core.hooksPath` feature that the Husky docs mention was introduced in Git 2.9.
