### ISSUE TITLE
Doesn't work where python 2 is default

### ISSUE THREAD

**Issue by chiptopher** [chiptopher/guet#13]
## Bug report
When I go to commit on a fresh install in OSX mojave, it throws an error, saying it can't import a certain module.

#### Actual behavior?
It throws an error.

#### Expected behavior?
It doesn't throw an error.

#### Environment:
Python 2 on OSX mojave

**Comment by dpainte7** [comment]
I ran into this on Mac OSX as well where Python2 was the default installation.  Python 3 is installed via homebrew at /usr/local/bin/python3.

At first, when trying to commit, I saw the module error and the commit didn't go through.  After making the change you recommended above, I still see the module error, but the commit does go through.  

Any thoughts?

**Comment by chiptopher** [comment]
It's probably the post-commit hook throwing that error. The post-commit hook rotates who is considered the "author" of the commit, but nothing else. It won't stop you from development, you'll just lose out of that piece.

I'm working on a fix that'll let you initialize the commit hooks to explicitly use python3 rather than whatever the system default python is with a `--python3` flag.

**Comment by chiptopher** [comment]
This should be addressed in ec09fd2c6e05487d5b0e7edb2f4f4ee6c005754c. If you pull down the most recent version from pypi and delete the current git hooks, you should be able to remake them with the `--python3` flag.

**Comment by meganmajewski** [comment]
Your most recent change works, thanks!  Maybe there should be a READMe note as well documenting this option?

**Comment by chiptopher** [comment]
Done!
