### ISSUE TITLE
"Must set pairs again" message is not emphatic or specific enough

### ISSUE THREAD

**Issue by sapphon** [chiptopher/guet#15]
I would like it to be more clear when a 'git commit' command fails because guet pairs aren't set.

#### Environment:
Flabs pairing station

#### Context
As a guet user
I want it to be more obvious when guet prevents a commit
So that I can notice and do what I need to do to commit 

#### Acceptance Criteria
Given that I have guet configured on a Git repository
When I use 'git commit' without having used 'guet set' recently
Then my failure message is very clear and emphatic about the fact a commit wasn't made

**Comment by chiptopher** [comment]
This should be addressed in 7b7092c572928a14a957e2d519ec46f212903c30 and was made available in 1.0.2
