### ISSUE TITLE
'guet get'

### ISSUE THREAD

**Issue by sapphon** [chiptopher/guet#24]
### Optional user story format:
As a developer
I want to be able to query Guet for the currently set pair
So that I can know whether a 'guet set' worked the way I expected.

### Current Behavior
Tanmay: Why did this commit from you come in as me?
Me: I don't know.  I did 'guet set cs mw'.  You're 'ts'.
Tanmay: -_-

### Desired Behavior:
Tanmay: Why did this commit from you come in as me?
Me: I don't know.  Let me check what pair guet has set.
Me: *checks* Oh.  It's still set to you for some reason.
Tanmay: -_-

**Comment by chiptopher** [comment]
Addressed in the 2.1.0 release.
