### ISSUE TITLE
Print helpful common error messages out to terminal

### ISSUE THREAD

**Issue by dpainte7** [chiptopher/guet#68]
## Feature Request
Right now guet prints all errors to an error file.  It would be a lot more convenient in the case of common errors (for example, if I'm not in a directory with a .git file) for guet to just print out a nice error message directly.

#### Description
Description of the feature, and why it might be beneficial.

#### Example
Example of feature in use in the following format:
```
$ (in directory with no .git)
$ guet set <initials>
$ OLD: An error has occurred, please refer to error logs (~/.guet/errors) for more information
$ NEW: You must be in a directory with a .git file to set committers.
```
I think there are probably several more error cases where a similar approach would be really useful.  I don't like having to look at the log file.

**Comment by chiptopher** [comment]
Good find. The "An error has occurred, please refer to error logs (~/.guet/errors)" message is basically a catch all for any errors I didn't program to catch.

Do you have any information for me about what you were doing that caused that error so I can try and wrap it with a good error message? Also, what is your guet version?

**Comment by dpainte7** [comment]
I'm on 2.3.6, and I was two directories deep into my repo when I executed ```guet set <>``` and got that error.  It seems like it doesn't traverse up and look for the .git in the parent directories?

**Comment by chiptopher** [comment]
Okay. I've created a new issue #69 to address that issue specifically.

I'm going to close the issue for now, but if you get the global error message again slap the output of the error file in a new issue and I'll cover it with a warning!
