### ISSUE TITLE
Don't show "guet successfully started" message after cancelling the request

### ISSUE THREAD

**Issue by dulcimerist** [chiptopher/guet#88]
## Bug report
When I type "X"  in the ```guet start``` prompt regarding git hooks already existing, I still see ```guet successfully started in this repository.```, which is a lie upon inspecting my git hook files.

#### Environment:
Mac OSX 10.14.6
Python 2.7.16

**Comment by chiptopher** [comment]
Deployed with version [2.4.6](https://github.com/chiptopher/guet/blob/master/.github/CHANGELOG.md)
