### ISSUE TITLE
Add uninstall documentation, please 🙂

### ISSUE THREAD

**Issue by tishathomas2019** [chiptopher/guet#94]
#### Description
I heard about guet, and then tried it when pair programming, but then we decided to not use it afterall. So I removed myself and my coworker from guet, and then tried to just do a regular commit. However, it wouldn't let me commit unless I set the commiters! This was frustrating, so I asked someone for help and they suggested I run the command `pip3 uninstall guet`. This worked to remove guet from my computer, but I really think you should add this to your README for people like me who would like to remove it from their machine 🙃

**Comment by chiptopher** [comment]
Sorry that happened to you! This is a good call though, so I'll include something in there somewhere. I'm thinking I'd put it in the FAQ, or do you think I should put it directly in the README?

**Comment by tishathomas2019** [comment]
Well I checked the README and also the FAQ, and didn't find uninstall documentation in either place, so I think either of those two places would work!
