### ISSUE TITLE
Add way to remove guet from initialized repo

### ISSUE THREAD

**Issue by tishathomas2019** [chiptopher/guet#95]
## Feature Request
It would be great if you could add a way to `uninitialize` guet from a repo after initializing it 🙂To get rid of it from my repo, I had to remove it from my entire computer! Someday I might use it again, but will have to just install it again when I want to use it.

#### Description
Add a command `guet uninit` so they can undo a `guet init`. This would be beneficial because then the user could stop using it in their repo but still keep it installed on their machine for future use cases.

**Comment by chiptopher** [comment]
I like this. I should be able to get to it over the weekend. Thanks for the request!

**Comment by tishathomas2019** [comment]
Cool! Thanks Chris! :D

**Comment by tishathomas2019** [comment]
Not sure if this should be a new issue or not - but after uninstalling `guet` with `pip3 uninstall guet`, it wouldn't let me do a regular commit.. 😬This is the error message that displayed:

```
Traceback (most recent call last):
  File ".git/hooks/pre-commit", line 2, in <module>
    from guet.hooks import manage
ModuleNotFoundError: No module named 'guet'
```

I guess `guet` is intertwined in my repo now, so just uninstalling it didn't take care of the whole issue - but I just got `guet` again, added only myself as the committer, and will just leave it at that! Didn't realize there would be further complications after uninstalling the software, so this is the easy way out 🙃

**Comment by chiptopher** [comment]
I should have clarified earlier that there was this extra step, my bad! guet uses git hooks under the hood, so when you `guet start` in a repo, it basically creates a `pre-commit`, `post-commit`, and `commit-msg` hook under your projects `.git/hooks/` folder. Even if you uninstall guet with through `pip3`, it won't get rid of them.

The good news is that they don't get tracked by version control, so you can remove them without affecting your project. Using guet even if you aren't pairing is also an option. As odd as it sounds, you wouldn't be the first person to do it.
